### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [patti-favaron/datetime#3]
I suggest adding topics such as `date`, `time`, `datetime` in the About section at https://github.com/patti-favaron/datetime

**Comment by patti-favaron** [comment]
Thanks! I'll add, as soon as having some time. Soon, by the way.

**Comment by patti-favaron** [comment]
I've extended the README.md file with definition of the data type, functions and operators.

Is this what you were looking for? 😊

(Maybe it wasn't, but, it was indeed quite needed.)

**Comment by Beliavsky** [comment]
No, how to add topics is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by patti-favaron** [comment]
Thanks! Topics added.
